import React, { useState } from 'react';
import { usePatientData } from '../context/PatientDataContext';

export const HealthSummaryPage: React.FC = () => {
  const { organs, profile, user, isLoading, error, reload } = usePatientData();
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownloadPDF = () => { window.print(); };

  const handleRegenerate = () => {
    setIsGenerating(true);
    setTimeout(() => setIsGenerating(false), 1200);
  };

  const statusColor = (status: string) => {
    if (status === 'MONITOR') return 'text-amber-500';
    if (status === 'ABNORMAL') return 'text-rose-500';
    if (status === 'CRITICAL') return 'text-red-600';
    return 'text-emerald-500';
  };

  const statusIcon = (status: string) => {
    if (status === 'CARDIOVASCULAR') return 'favorite';
    if (status === 'RESPIRATORY') return 'pulmonology';
    if (status === 'NERVOUS') return 'psychology';
    if (status === 'RENAL') return 'nephrology';
    if (status === 'HEPATIC') return 'medication_liquid';
    if (status === 'DIGESTIVE') return 'gastroenterology';
    return 'monitor_heart';
  };

  if (isLoading) {
    return (
      <div className="w-full flex-1 flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-slate-400 text-sm">Loading health summary...</p>
        </div>
      </div>
    );
  }

  if (error && organs.length === 0) {
    return (
      <div className="w-full flex-1 flex flex-col items-center justify-center gap-3 py-20 text-center">
        <span className="material-symbols-outlined text-rose-400 text-[48px]">cloud_off</span>
        <p className="text-slate-800 font-bold">Failed to Load Health Summary</p>
        <p className="text-slate-500 text-sm">{error}</p>
        <button onClick={reload} className="mt-2 px-5 py-2 rounded-xl bg-blue-600 text-white text-sm font-semibold hover:bg-blue-700">Retry</button>
      </div>
    );
  }

  return (
    <div className="w-full flex-1 flex flex-col p-4 md:p-8 max-w-6xl mx-auto overflow-y-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-100">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">AI Health Summary & Clinical Report</h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Holistic digital twin multi-organ evaluation generated by MedTwin Bio-Intelligence
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="flex items-center gap-1.5 px-4 py-2 rounded-full border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 shadow-2xs transition-all"
          >
            <span className={`material-symbols-outlined text-[16px] text-blue-600 ${isGenerating ? 'animate-spin' : ''}`}>
              refresh
            </span>
            {isGenerating ? 'Analyzing...' : 'Regenerate'}
          </button>
          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-1.5 px-5 py-2 rounded-full bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-md shadow-blue-500/20 transition-all"
          >
            <span className="material-symbols-outlined text-[16px]">download</span>
            Download PDF
          </button>
        </div>
      </div>

      {/* Main Report Card */}
      <div className="bg-white rounded-3xl p-6 md:p-8 border border-slate-100 shadow-xs my-6 flex flex-col gap-6">
        {/* Patient Header Block */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
          <div className="flex items-center gap-3.5">
             <div className="w-12 h-12 rounded-full bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center ring-2 ring-white shadow-xs">
               <span className="text-white text-xl font-black">{user?.name?.charAt(0)?.toUpperCase() ?? 'P'}</span>
             </div>
             <div>
               <h2 className="text-sm font-bold text-slate-900">{user?.name ?? '—'}</h2>
               <p className="text-xs text-slate-400">
                 {profile?.bloodGroup ? `Blood Group: ${profile.bloodGroup}` : ''}
                 {profile?.gender ? ` • ${profile.gender}` : ''}
                 {profile?.dateOfBirth ? ` • DOB: ${new Date(profile.dateOfBirth).toLocaleDateString()}` : ''}
               </p>
             </div>
           </div>
          <div className="text-right">
            <div className="text-xs font-semibold text-emerald-600 flex items-center justify-end gap-1">
              <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
              Digital Twin Score: 96 / 100
            </div>
            <p className="text-[10px] text-slate-400">Report Date: Today, 08:30 AM</p>
          </div>
        </div>

        {/* AI Executive Summary */}
        <div className="flex flex-col gap-2">
          <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <span className="material-symbols-outlined text-blue-600 text-[18px]">auto_awesome</span>
            Executive Bio-Twin Synthesis
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed font-normal bg-blue-50/50 p-4 rounded-2xl border border-blue-100/60">
            Hardish's continuous telemetry exhibits exemplary cardiovascular and metabolic equilibrium. Resting heart rate of 78 bpm demonstrates steady sinus rhythm with no ectopic deviations. Arterial pressure at 120/80 mmHg remains tightly controlled with prescribed Amlodipine regimen. Pulmonary gas exchange (SpO2 98%) and renal clearance parameters (eGFR 102 mL/min) confirm robust systemic homeostasis.
          </p>
        </div>

        {/* Multi-Organ Health Breakdown */}
        <div className="flex flex-col gap-3">
          <h3 className="text-sm font-bold text-slate-900">Organ System Breakdown</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
             {organs.length === 0 ? (
               <p className="text-xs text-slate-400 col-span-2">No organ system data available.</p>
             ) : organs.slice(0, 8).map((organ) => (
               <div
                 key={organ.id}
                 className="group p-4 rounded-2xl border border-slate-100/90 bg-white/60 shadow-2xs hover:bg-white hover:border-blue-300/80 hover:shadow-lg hover:shadow-blue-500/5 hover:-translate-y-0.5 transition-all duration-300 ease-out flex flex-col gap-1.5 cursor-pointer"
               >
                 <div className="flex items-center justify-between">
                   <span className="text-xs font-bold text-slate-900 group-hover:text-blue-600 transition-colors duration-200 capitalize flex items-center gap-2">
                     <span className="material-symbols-outlined text-blue-600 text-[18px] transition-transform duration-300 ease-out group-hover:scale-115 group-hover:rotate-6">
                       {statusIcon(organ.system)}
                     </span>
                     {organ.system.charAt(0) + organ.system.slice(1).toLowerCase()}
                   </span>
                   <span className={`text-xs font-bold ${statusColor(organ.status)}`}>
                     ● {organ.status.charAt(0) + organ.status.slice(1).toLowerCase()}
                   </span>
                 </div>
                 <p className="text-[11px] text-slate-500 leading-relaxed font-normal">{organ.summary || 'Status within normal limits.'}</p>
               </div>
             ))}
           </div>
        </div>
      </div>
    </div>
  );
};
